---
name: ci

on:
  workflow_dispatch:
  pull_request_target:
    types: [ labeled, opened, synchronize, reopened, auto_merge_enabled ]
  push:
    branches:
      - main
    paths:
      - "*/**"

permissions:
  issues: write
  pull-requests: write
  contents: read
  security-events: write
  actions: read
  packages: write

env: 
  GIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
  
jobs:
  ci:
    runs-on: ubuntu-latest
    env: {}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Go
        run: |
          go mod tidy
          go mod verify
          go test ./...
          go vet ./...
      - name: Docker Build
        run: |
          docker build \
            --rm \
            --label org.opencontainers.image.authors='TheAuthors <the.authors@acme.corp>' \
            --label org.opencontainers.image.vendor='TheAuthors <the.authors@acme.corp>' \
            --label org.opencontainers.image.version='${{ github.sha }}' \
            --label org.opencontainers.image.revision='${{ github.sha }}' \
            --label org.opencontainers.image.source='https://github.com/${{ github.repository }}' \
            -t onbuild:onbuild \
            -f Dockerfile \
            .
          docker tag onbuild:onbuild ghcr.io/${{ github.repository_owner }}/onbuild:${{ github.sha }}
      - name: Container Structure Test
        run: |
          docker run \
            --rm \
            --name container-structure-test \
            -v $(pwd)/imagetest.yaml:/imagetest.yaml \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -t gcr.io/gcp-runtimes/container-structure-test:latest \
              test --image onbuild:onbuild --config /imagetest.yaml
      - name: Container Scan via Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'onbuild:onbuild'
          format: 'sarif'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-results.sarif